### ISSUE TITLE
Issue with running BaM + FixMatch 

### ISSUE THREAD

**Issue by NamburiSrinath** [clott3/BaM-SSL#1]
Hi @clott3,

Thanks for the repo :) 

I'm facing an issue when running the repo with the following command

`python train_bayes_cifar.py --dataset=cifar10 --num_labeled=2000 --bayes --final_quan=0.95 --bayes_lr=0.005 --epochs 1000 --eval_step 50`

Error - 
```
Using Reparam Bayes linear classifier 128, 10
Total params: 1.47M
Traceback (most recent call last):
  File "/hdd4/srinath2/BaM-SSL/train_bayes_cifar.py", line 681, in <module>
    main(args)
  File "/hdd4/srinath2/BaM-SSL/train_bayes_cifar.py", line 217, in main
    model.load_state_dict(checkpoint['state_dict']) # load model
  File "/hdd4/srinath2/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BayesCEWideResNet:
        Missing key(s) in state_dict: "fc.mu_weight", "fc.rho_weight", "fc.mu_bias", "fc.rho_bias".         Unexpected key(s) in state_dict: "fc.weight", "fc.bias".
```

I am thinking the class `BayesCEWideResNet` has these keys missing and am trying to figure out. 
Incase you have an idea, can you please help me out?

Looking forward

**Comment by NamburiSrinath** [comment]
Sorry for the trouble, I figured out the issue. As I am running multiple experiments with different settings, I've to pass the `"exp"` flag 

`python train_bayes_cifar.py --dataset=cifar10 --num_labeled=2000 --bayes --final_quan=0.95 --bayes_lr=0.005 --epochs 1000 --eval_step 50 --exp Exp2`

Now it's executing :)

Closing this issue!
